app:
  path-book: 'D:\Himic\.Books'      # Directory for book/comic files
  path-config: 'D:\Himic\.Config\BookLore'   # Directory for thumbnails, metadata, etc.

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3333/booklore?createDatabaseIfNotExist=true
    username: root
    password: Password123